@startuml

actor User

participant "API Gateway" as APIGW
participant "Payment Query Service" as Query
participant "Payment Query DB" as QueryDb
participant "Wallet Service" as Wallet
participant "Wallet DB" as WalletDb
queue "Kafka Broker" as KafkaWallet
participant "Transactional DB" as TransactionalDb
participant "Transactional Service" as Transactional
participant "Payment Service" as Payment
participant "Payment DB" as PaymentDb
queue "Kafka Broker" as KafkaCallback
participant "Callback Service" as Callback
participant "Callback DB" as CallbackDb
participant "Callback Gateway" as CallbackGw
participant "Resilence HTTP Client\n(Retry + CB + Bulkhead)" as Resilence
participant "External Payment Provider" as ExtProvider

== Клиент инициирует платеж ==

User -> APIGW: POST (создать платёж)
APIGW -> Wallet: Запрос на платеж (сумма, получатель)

Wallet -> WalletDb: Создать транзакцию (status=NEW)
Wallet --> WalletDb: commit (локальная транзакция)
Wallet -> WalletDb: Списать сумму (резерв средств)
Wallet -> WalletDb: Сохранить транзакцию (status=PENDING)
Wallet -> WalletDb: Записать событие\n"PaymentInitiated" в Outbox
Wallet --> WalletDb: commit (локальная транзакция)

Wallet -> KafkaWallet: публикует событие PaymentInitiated\n(через Outbox + polling)

KafkaWallet -> Transactional: доставить событие PaymentInitiated
KafkaWallet -> Query: доставить событие PaymentInitiated
Query -> QueryDb : Записать событие
Query --> QueryDb : commit (локальная транзакция)

Transactional -> TransactionalDb: Сохранить платеж (status=PENDING)
Transactional --> TransactionalDb: commit (локальная транзакция)

Transactional -> Payment: Вызвать API провайдера\n(списание средств)
Payment -> PaymentDb: Сохранить платеж (status=CALLING_PROVIDER)
Payment --> PaymentDb: commit (локальная транзакция)

== Первая попытка вызова провайдера ==

Payment -> Resilence: Вызвать API провайдера
Resilence -> ExtProvider: Вызвать API провайдера

Resilence -> Resilence: timeout (превышен 1s)
Resilence --> Payment: ERROR (timeout)
Payment -> Payment: отмечаем 1 ошибку в статистике СВ

== Retry с backoff ==

loop Retry (maxAttempts=3,\n exponential backoff + jitter)

Payment -> Resilence: Вызвать API провайдера
Resilence -> ExtProvider: Вызвать API провайдера
Resilence -> Resilence: timeout (превышен 1s)
Resilence --> Payment: ERROR (timeout)
Payment -> Payment: увеличиваем счетчик ошибок,\nпроверяем порог СВ
end

== Circuit Breaker открывается ==

Payment -> Payment: CircuitBreaker = OPEN\nне ходим к провайдеру некоторое время

== Fallback для новых запросов ==

User -> APIGW: POST (создать платёж)
APIGW -> Wallet: Запрос на платеж (сумма, получатель)

Wallet -> WalletDb: Создать транзакцию (status=NEW)
Wallet --> WalletDb: commit (локальная транзакция)
Wallet -> WalletDb: Списать сумму (резерв средств)
Wallet -> WalletDb: Сохранить транзакцию (status=PENDING)
Wallet -> WalletDb: Записать событие\n"PaymentInitiated" в Outbox
Wallet --> WalletDb: commit (локальная транзакция)

Wallet -> KafkaWallet: публикует событие PaymentInitiated\n(через Outbox + polling)

KafkaWallet -> Transactional: доставить событие PaymentInitiated
KafkaWallet -> Query: доставить событие PaymentInitiated
Query -> QueryDb : Записать событие
Query --> QueryDb : commit (локальная транзакция)

Transactional -> TransactionalDb: Сохранить платеж (status=PENDING)
Transactional --> TransactionalDb: commit (локальная транзакция)
Transactional -> Payment: Вызвать API провайдера\n(списание средств)

Payment -> Payment: видим CB в состоянии OPEN
Payment -> PaymentDb: Сохранить платеж (status=PENDING_PROVIDER)
Payment --> PaymentDb: commit (локальная транзакция)
Payment -> Transactional: доставить событие PaymentResult (PENDING_PROVIDER)

Transactional -> TransactionalDb: Обновить статус транзакции = PENDING_PROVIDER
Transactional --> TransactionalDb: commit (локальная транзакция)
Transactional -> KafkaWallet: доставить событие PaymentResult (PENDING_PROVIDER)

KafkaWallet -> Query: доставить событие PaymentResult (PENDING_PROVIDER)
Query -> QueryDb : Записать событие (PENDING_PROVIDER)
Query --> QueryDb : commit (локальная транзакция)

KafkaWallet -> Wallet: доставить событие PaymentResult (PENDING_PROVIDER)\n
Wallet -> WalletDb: Обновить статус транзакции = PENDING_PROVIDER
Wallet --> WalletDb: commit (локальная транзакция)
Wallet -> APIGW: 202 Accepted (PENDING)

APIGW -> User: платеж в процессе обработки


@enduml
