@startuml

actor User

participant "API Gateway" as APIGW
participant "Payment Query Service" as Query
participant "Payment Query DB" as QueryDb
participant "Wallet Service" as Wallet
participant "Wallet DB" as WalletDb
participant "Kafka Broker" as KafkaWallet
participant "Transactional DB" as TransactionalDb
participant "Transactional Service" as Transactional
participant "Payment Service" as Payment
participant "Kafka Broker" as KafkaCallback
participant "Callback Service" as Callback
participant "Callback DB" as CallbackDb
participant "Callback Gateway" as CallbackGw
participant "External Payment Provider" as ExtProvider

User -> APIGW: POST (создать платёж)
APIGW -> Wallet: Запрос на платеж (сумма, получатель)

Wallet -> WalletDb: Создать транзакцию (status=NEW)
Wallet --> WalletDb: commit (локальная транзакция)
Wallet -> WalletDb: Списать сумму (резерв средств)
Wallet -> WalletDb: Сохранить транзакцию (status=PENDING)
Wallet -> WalletDb: Записать событие\n"PaymentInitiated" в Outbox
Wallet --> WalletDb: commit (локальная транзакция)

Wallet -> KafkaWallet: публикует событие PaymentInitiated\n(через Outbox + polling)

KafkaWallet -> Transactional: доставить событие PaymentInitiated
KafkaWallet -> Query: доставить событие PaymentInitiated
Query -> QueryDb : Записать событие
Query --> QueryDb : commit (локальная транзакция)

Transactional -> TransactionalDb: Сохранить платеж (status=PENDING)
Transactional --> TransactionalDb: commit (локальная транзакция)

Transactional -> Payment: Вызвать API провайдера через Gateway\n(списание средств)
Payment -> ExtProvider: Вызвать API провайдера\n(списание средств)

Transactional -> TransactionalDb: Обновить статус платежа (status=SENT)
Transactional --> TransactionalDb: commit (локальная транзакция)

ExtProvider -> CallbackGw: платеж успешен (SUCCESS)
CallbackGw -> Callback: Callback: платеж успешен (SUCCESS)

Callback -> CallbackDb : Сохранить статус платежа (SUCCESS)
Callback --> CallbackDb : commit (локальная транзакция)
Callback -> KafkaCallback: публикует событие PaymentResult (SUCCESS)\n(через Outbox + polling)
KafkaCallback -> Transactional: доставить событие PaymentResult (SUCCESS)

Transactional -> TransactionalDb: Обновить статус платежа\n(SUCCESS)
Transactional -> TransactionalDb: Записать событие \n"PaymentResult" в Outbox
Transactional --> TransactionalDb: commit (локальная транзакция)

Transactional -> KafkaWallet: публикует событие PaymentResult (SUCCESS)

note over Transactional
  Таймер ожидания callback
  timeout = 3s
end note
alt Transactional received after timeout
    Transactional -> TransactionalDb: Записать событие \n"PaymentResult" в Outbox
    Transactional --> TransactionalDb: commit (локальная транзакция)
    Transactional -> KafkaWallet: публикует событие PaymentResult (FAILED_TIMEOUT)
end

KafkaWallet -> Query: доставить событие PaymentResult (SUCCESS/FAILED_TIMEOUT)
Query -> QueryDb : Записать событие (SUCCESS/FAILED_TIMEOUT)
Query --> QueryDb : commit (локальная транзакция)

KafkaWallet -> Wallet: доставить событие PaymentResult (SUCCESS/FAILED_TIMEOUT)\n
Wallet -> WalletDb: Подтвердить списание\n(окончательное списание)
Wallet -> WalletDb: Обновить статус транзакции = Completed
Wallet --> WalletDb: commit (локальная транзакция)


User -> APIGW: GET (получить данные по платёжу)
APIGW -> Query: Запрос на получение данных по платежу

@enduml
