@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


System_Boundary(payment, "Transactional Service") {

    Component(consumer_pi, "PaymentInitiated Consumer", "Kafka Consumer", "Получает событие и запускает процесс списания")
    Component(callback_api, "CallbackController", "REST Controller", "Обрабатывает callback от провайдера")
    Component(deadline, "DeadLine Service", "Scheduler", "Fail-ит просроченные платежи")
    Component(domain, "Domain Model", "Domain", "Статусы платежа, retry, ошибки")
    Component(repo, "TransactionalRepository", "PostgreSQL DAO", "Хранение платежей")
    Component(outboxWallet, "Outbox", "Relational Outbox", "Запись PaymentResult")
    Component(outboxPayment, "Outbox", "Relational Outbox", "Запись PaymentInitiated")
}

ComponentDb(payment_db, "Transactional DB", "PostgreSQL", "Данные о платежах")
Rel(deadline, repo, "read/write")
Rel(repo, payment_db, "read/write")
Rel(outboxWallet, payment_db, "хранит события")

System_Ext(provider, "External Payment Provider", "Gateway")
System_Ext(kafkaWallet, "Kafka")
System_Ext(kafkaPayment, "Kafka")

Rel(consumer_pi, domain, "Создать платеж")
Rel(domain, outboxWallet, "PaymentResult")
Rel(domain, outboxPayment, "PaymentInitiated")
Rel(deadline, outboxWallet, "PaymentResult")
Rel(domain, repo, "Создать/обновить платеж")
Rel(provider, callback_api, "Callback (SUCCESS/FAIL)")
Rel(callback_api, domain, "Обновить статус")
Rel(outboxWallet, kafkaWallet, "PaymentResult")
Rel(outboxPayment, kafkaPayment, "PaymentInitiated")
Rel(kafkaWallet, consumer_pi, "Создание платежа")

@enduml