@startuml

participant "Kafka Broker" as Kafka
participant "Wallet Service" as Wallet
participant "Wallet DB" as WalletDb
participant "payments.wallet.dlq" as DLQ
participant "Minio" as Minio
participant "Support" as Support
participant "DLQ Service" as DLQService

Kafka -> Wallet: PaymentResult

alt Попытка #1
    Wallet -> Wallet: Ошибка маппинга
    Wallet -> Wallet: Увеличиваем счетчик попыток
    Wallet -> Kafka: Commit offset = NO
end

alt Попытка #2
    Kafka -> Wallet: Повторное чтение PaymentResult
    Wallet -> Wallet: Ошибка маппинга
    Wallet -> Wallet: Увеличиваем счетчик попыток
    Wallet -> Kafka: Commit offset = NO
end

alt Попытка #3 (Количество попыток закончилось)
    Kafka -> Wallet: Повторное чтение PaymentResult
    Wallet -> Wallet: Количество попыток закончилось
    Wallet -> DLQ: Отправляем сообщение в DLQ
    Wallet -> Kafka: Commit offset = YES
    DLQ -> Minio: Сохраняем в Minio
end

Support -> Minio: Ручной разбор
Support -> DLQService: Действие после ручного разбора\n(retry / fix / ignore)

alt Разбор ошибки и перезапуск сообщения (если нужно)
    DLQService -> Minio: Формируем сообщение
    DLQService -> Wallet: PaymentResult
    Wallet -> WalletDb: SUCCESS/FAILED status
    WalletDb --> Wallet: OK
end

@enduml
