@startuml

actor User

participant "API Gateway" as APIGW
participant "Payment Query Service" as Query
participant "Payment Query DB" as QueryDb
participant "Wallet Service" as Wallet
participant "Wallet DB" as WalletDb
participant "Kafka Broker" as Kafka
participant "Transactional DB" as TransactionalDb
participant "Transactional Service" as Transactional
participant "Payment Service" as Payment
participant "Callback Service" as Callback
participant "Callback DB" as CallbackDb
participant "Callback Gateway" as CallbackGw
participant "External Payment Provider" as ExtProvider

User -> APIGW: POST (создать платёж)
APIGW -> Wallet: Запрос на платеж (сумма, получатель)

Wallet -> WalletDb: Создать транзакцию (status=NEW)
Wallet --> WalletDb: commit (локальная транзакция)
Wallet -> WalletDb: Списать сумму (резерв средств)
Wallet -> WalletDb: Сохранить транзакцию (status=PENDING)
Wallet -> WalletDb: Записать событие\n"PaymentInitiated" в Outbox
Wallet --> WalletDb: commit (локальная транзакция)

Wallet -> Kafka: публикует событие PaymentInitiated\n(через Outbox + polling)

Kafka -> Transactional: доставить событие PaymentInitiated
Kafka -> Query: доставить событие PaymentInitiated
Query -> QueryDb : Записать событие
Query --> QueryDb : commit (локальная транзакция)

Transactional -> TransactionalDb: Сохранить платеж (status=PENDING)
Transactional --> TransactionalDb: commit (локальная транзакция)

Transactional -> Payment: Вызвать API провайдера через Gateway\n(списание средств)
Payment -> ExtProvider: Вызвать API провайдера\n(списание средств)

Transactional -> TransactionalDb: Обновить статус платежа (status=SENT)
Transactional --> TransactionalDb: commit (локальная транзакция)

ExtProvider -> CallbackGw: платеж неуспешен (FAILED)
CallbackGw -> Callback: Callback: платеж неуспешен (FAILED)

Callback -> CallbackDb : Сохранить статус платежа (FAILED)
Callback --> CallbackDb : commit (локальная транзакция)
Callback -> Kafka: публикует событие PaymentResult (FAILED)\n(через Outbox + polling)
Kafka -> Transactional: доставить событие PaymentResult (Fail)

Transactional -> TransactionalDb: Обновить статус платежа (FAILED)\n(Success)
Transactional -> TransactionalDb: Записать событие\n"PaymentResult" в Outbox
Transactional --> TransactionalDb: commit (локальная транзакция)

Transactional -> Kafka: публикует событие PaymentResult (FAILED)


note over Transactional
  Таймер ожидания callback
  timeout = 3s
end note
alt Transactional received after timeout
    Transactional -> TransactionalDb: Записать событие \n"PaymentResult" в Outbox
    Transactional --> TransactionalDb: commit (локальная транзакция)
    Transactional -> Kafka: публикует событие PaymentResult (FAILED_TIMEOUT)
end

Kafka -> Query: доставить событие PaymentResult (FAILED/FAILED_TIMEOUT)
Query -> QueryDb : Записать событие (FAILED/FAILED_TIMEOUT)
Query --> QueryDb : commit (локальная транзакция)

Kafka -> Wallet: доставить событие PaymentResult (FAILED/FAILED_TIMEOUT)\n
Wallet -> WalletDb: Компенсация: вернуть\n зарезервированные средства
Wallet -> WalletDb: Обновить статус транзакции = FAILED/FAILED_TIMEOUT
Wallet --> WalletDb: commit (локальная транзакция)

User -> APIGW: GET (получить данные по платёжу)
APIGW -> Query: Запрос на получение данных по платежу

@enduml
